PHP/learnLaravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\HomeController;



Route::middleware(['auth'])->group(function (){
	Route::get('/', [HomeController::class, 'index']);
	Route::group([
		'as'=>'admin.',
		'middleware'=>'is_admin',
		'prefix'=>'admin'
	],function(){

		Route::get('/', [\App\Http\Controllers\HomeController::class,'index']);

		Route::resource('/product', \App\Http\Controllers\ProductController::class);

		Route::resource('/category', \App\Http\Controllers\CategoryController::class);

		Route::resource('/task', \App\Http\Controllers\TaskController::class);

		// Route::get('/category', [\App\Http\Controllers\CategoryController::class,'index'])->name('category.list')->middleware(['can:admin']);

		Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class,'logout'])->name('logout');

	});
	
});



Route::get('/admin/login', function () {
    return view('admin.page.auth.login');
})->name('login');

Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class,'login'])->name('login');

PHP/learnLaravel/app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Colors;
use App\Models\ProductColor;

class Products extends Model
{
    use HasFactory;
    //có thể insert vào
    protected $fillable = ['name', 'price','description','image'];
    protected $primaryKey = 'id';
 	protected $table = 'products';

 	public function colors()
 	{
 		return $this->belongsToMany(Colors::class,ProductColor::class,'product_id','color_id');
 	}
}

PHP/learnLaravel/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Products;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $keyword='';
        $data=[];
        //$products=Products::all()->load('colors');
        $products=Products::when($keyword, function($query) use ($keyword){
            $query->whereHas('colors', function($q) use ($keyword){
                $q->where('id',$keyword); // for Colors
            });
        });//->where('id',48) for Products
        $products=$products->orderBy('id','desc')->paginate(10);
        // foreach ($products as $key => $product) {
        //     dd(count($product->colors));
        //     $data[]=$product->colors;
        // }
        // dd($data);
        return view('admin.page.product.index')->with(compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Products $product)
    {
        //
        return view('admin.page.product.edit')->with(compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

PHP/learnLaravel/resources/views/admin/page/product/create.blade.php
@extends('admin.layouts.main', ['title' => 'Thêm Sản Phẩm'])
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @include('admin.page.view-header',['title_view'=>'Thêm Sản Phẩm'])

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection

PHP/learnLaravel/resources/views/admin/page/product/edit.blade.php
@extends('admin.layouts.main', ['title' => 'Sản Phẩm'])
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @include('admin.page.view-header',['title_view'=>'Sữa Sản Phẩm'])
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header d-flex align-items-center ">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
              </div>
              <div class="card-body">
                <form method="POST" action="{{route('admin.product.update',[$product->id])}}"  enctype='multipart/form-data'>
                      @method('PUT')
                      @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Sản Phẩm</label>
                        <input type="text" class="form-control" value="{{$product->name}}" name="name" id="slug" aria-describedby="emailHelp">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Giá</label>
                        <input type="text" class="form-control" value="{{number_format($product->price,0,',','.')}}" name="name" id="slug" aria-describedby="emailHelp">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mô tả sản phẩm</label>
                        <input type="text" class="form-control" value="{{$product->description}}" name="description" id="exampleInputEmail1" aria-describedby="emailHelp">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Hình Ảnh</label>
                        <img src="{{$product->image}}" alt="" class="w-15">
                      </div>
                      <button type="submit" class="btn btn-info">Cập Nhật</button>
                  </form> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection
@push('script')
<script type="text/javascript">
</script>
@endpush

PHP/learnLaravel/resources/views/admin/page/product/index.blade.php
@extends('admin.layouts.main', ['title' => 'Sản Phẩm'])
@push('styles')
<style type="text/css">
    .btnDetail{
      width: 67px;
      height: 34px;
      border-radius: 25px;
    }
</style>
@endpush
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @include('admin.page.view-header',['title_view'=>'Sản Phẩm'])

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header d-flex align-items-center ">
                <h3 class="card-title col-md-10">Danh sách thông tin sản phẩm</h3>
                <div class="col-md-2 d-flex justify-content-center">
                    <button class="btn btn-info">Thêm</button>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="datatable" class="table table-bordered table-hover">
                  <thead>
                    <tr>
                      <th></th>
                      <th>STT</th>
                      <th>Sản Phẩm</th>
                      <th>Giá</th>
                      <th>Mô Tả</th>
                      <th>Hình Ảnh</th>
                      <th style="width: 130px;" class="text-center">Thao Tác</th>
                    </tr>
                  </thead>
                  <tbody>
                  @foreach ($products as $key => $product)
                    <tr>
                      <td class="align-middle">
                        @if(count($product->colors)>0)
                          <button class="btn btn-success btnDetail" data-id="{{$key+1}}">
                            <i class="fas fa-list text-white"></i>&nbsp;{{count($product->colors)}}
                          </button>
                        @endif
                      </td>
                      <td class="align-middle">{{$key+1}}</td>
                      <td class="align-middle">{{$product->name}}</td>
                      <td class="align-middle">{{number_format($product->price,0,',','.')}}&nbsp;đ</td>
                      <td class="align-middle">{{$product->description}}</td>
                      <td class="text-center"><img src="{{$product->image}}" class="w-75"></td>
                      <td class="pt-3 text-center align-middle">
                        <a href="{{route('admin.product.edit',$product)}}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                        <a href="#" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                      </td>
                    </tr>
                    <tr class="childRow" style="display: none;"> 
                      <td colspan="7">
                        <table class="tbItems" rules="rows"> 
                          <thead> 
                            <tr> 
                              <th>ID</th> 
                              <th>Name</th> 
                              <th>Hex</th>
                              <th>Color</th>  
                            </tr> 
                          </thead> 
                          <tbody> 
                            @foreach ($product->colors as $color)
                               <tr> 
                                  <td>{{$color->id}}</td> 
                                  <td>{{$color->color}}</td> 
                                  <td>{{$color->hex}}</td> 
                                  <td style="background:#{{$color->hex}}"></td> 
                              </tr> 
                            @endforeach 
                          </tbody> 
                        </table> 
                      </td> 
                
                  </tr>
                  @endforeach
                  </tbody>
                </table>

                 
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <div class="row">
                    {!! $products->links() !!}
                </div>
              </div>
            </div>
          </div>
          <!-- /.col -->
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection
@push('script')
<script type="text/javascript">
// $('#datatable').DataTable();
$(".btnDetail").click(function(){ 
  var detail = $(this).parent().parent().next();
  var status = $(detail).css("display"); 
  if(status == "none") 
    $(detail).css("display", "block"); 
  else 
    $(detail).css("display", "none");
});
</script>
@endpush