PHP/learnLaravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\HomeController;



Route::middleware(['auth'])->group(function (){
	Route::get('/', [HomeController::class, 'index']);
	Route::group([
		'as'=>'admin.',
		'middleware'=>'is_admin',
		'prefix'=>'admin'
	],function(){

		Route::get('/', [\App\Http\Controllers\HomeController::class,'index']);

		Route::resource('/product', \App\Http\Controllers\ProductController::class);

		Route::resource('/category', \App\Http\Controllers\CategoryController::class);

		Route::resource('/task', \App\Http\Controllers\TaskController::class);

		// Route::get('/category', [\App\Http\Controllers\CategoryController::class,'index'])->name('category.list')->middleware(['can:admin']);

		Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class,'logout'])->name('logout');

	});
	
});



Route::get('/admin/login', function () {
    return view('admin.page.auth.login');
})->name('login');

Route::post('/admin/login', [\App\Http\Controllers\Auth\LoginController::class,'login'])->name('login');

PHP/learnLaravel/app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;
class Task extends Model
{
    use HasFactory;
    protected $fillable = ['user_id', 'name','description'];
    protected $primaryKey = 'id';
 	protected $table = 'tasks';

 	public function user() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

PHP/learnLaravel/app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $task=Task::orderBy('id','desc')->get();
        return view('admin.page.task.index')->with(compact('task'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->authorize('create',Task::class);
        return view('admin.page.task.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //
        $this->authorize('update',$task);
        return view('admin.page.task.edit')->with(compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //
        $this->authorize('delete',$task);
        // $task->delete();
        // return redirect()->back()->with('status','Xóa nhiệm vụ thành công');
    }
}

PHP/learnLaravel/resources/views/admin/page/task/create.blade.php
@extends('admin.layouts.main', ['title' => 'Nhiệm Vụ'])
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @include('admin.page.view-header',['title_view'=>'Thêm Nhiệm Vụ'])
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header d-flex align-items-center ">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
              </div>
              <div class="card-body">
                <form method="POST" action="{{route('admin.task.store')}}"  enctype='multipart/form-data'>
                      @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên nhiệm vụ</label>
                        <input type="text" class="form-control" value="{{old('name')}}" name="name" id="slug" aria-describedby="emailHelp" placeholder="Tên danh mục...">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mô tả danh mục</label>
                        <input type="text" class="form-control" value="{{old('description')}}" name="description" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Mô tả nhiệm vụ">
                      </div>
                      <button type="submit" class="btn btn-primary">Thêm</button>
                    </form> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection
@push('script')
<script type="text/javascript">
</script>
@endpush

PHP/learnLaravel/resources/views/admin/page/task/edit.blade.php
@extends('admin.layouts.main', ['title' => 'Nhiệm Vụ'])
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @include('admin.page.view-header',['title_view'=>'Sữa Nhiệm Vụ'])
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header d-flex align-items-center ">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
              </div>
              <div class="card-body">
                <form method="POST" action="{{route('admin.task.update',[$task->id])}}"  enctype='multipart/form-data'>
                      @method('PUT')
                      @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên nhiệm vụ</label>
                        <input type="text" class="form-control" value="{{$task->name}}" name="name" id="slug" aria-describedby="emailHelp" placeholder="Tên danh mục...">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mô tả danh mục</label>
                        <input type="text" class="form-control" value="{{$task->description}}" name="description" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Mô tả nhiệm vụ">
                      </div>
                      <button type="submit" class="btn btn-info">Cập Nhật</button>
                  </form> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection
@push('script')
<script type="text/javascript">
</script>
@endpush

PHP/learnLaravel/resources/views/admin/page/task/index.blade.php
@extends('admin.layouts.main', ['title' => 'Nhiệm Vụ'])
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @include('admin.page.view-header',['title_view'=>'Nhiệm Vụ'])
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header d-flex align-items-center ">
                <h3 class="card-title col-md-3">Danh sách nhiệm vụ được giao</h3>
                <div class="col-md-7 d-flex">
                 {{--  <form action="{{route('admin.task.list')}}" method="GET" class="d-flex w-75" id="myForm">
                  {{csrf_field()}}
                     <div class="input-group-prepend">
                        <button class="btn btn-info"><i class="fas fa-search"></i></button>
                    </div>
                    <input type="text" class="form-control" placeholder="Nhập tìm kiếm..." aria-label="Username" aria-describedby="basic-addon1" name="search" id="search" >
                  <button class="btn btn-info ml-2" onclick=""><i class="fas fa-spinner"></i></button>
                </form> --}}
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                  @can('create',\App\Models\Task::class)
                    <a class="btn btn-info" href="{{route('admin.task.create')}}">Thêm</a>
                  @endcan 
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="datatable" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>STT</th>
                    <th>Nhiệm Vụ</th>
                    <th>Mô Tả</th>
                    <th style="width: 115px;" class="text-center">Thao Tác</th>
                  </tr>
                  </thead>
                  <tbody>
                  @foreach ($task as $key => $value)
                  <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$value->name}}</td>
                    <td>{{$value->description}}</td>
                    <td class="pt-3 text-center d-flex justify-content-center">
                      @can('update',$value)
                        <a href="{{route('admin.task.edit',[$value->id])}}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                      @endcan
                      @can('delete',$value)
                      <form action="{{route('admin.task.destroy',[$value->id])}}" method="POST">
                        @method('DELETE')
                        @csrf
                        <a onclick="return confirm('Bạn muốn xóa nhiệm vụ này không?');" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                      @endcan
                    </td>
                  </tr>
                  @endforeach
                  </tbody>
                </table>
              </div>

              <!-- /.card-body -->
            </div>
          </div>
          <!-- /.col -->
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection
@push('script')
<script type="text/javascript">
  $('#datatable').DataTable();
  function reset()
  {
    console.log("minh");
    document.getElementById("myForm").reset();
  }
</script>
@endpush